CREATE TABLE USERINFO
(
    USERID VARCHAR2(15), 
    PASSWD VARCHAR2(15)     NOT NULL,
    ADDR   VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK_USERID PRIMARY KEY(USERID)
);

INSERT INTO USERINFO(USERID, PASSWD, ADDR)VALUES('user01','1234','노원구 상계동 100번지');
COMMIT;
SELECT USERID, PASSWD, ADDR FROM USERINFO;

DELETE FROM USERINFO WHERE USERID = "user01";